# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Gradle build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install specific version of Chrome
      run: |
        CHROME_VERSION=131.0.6778.264
        wget https://dl.google.com/linux/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}-1_amd64.deb
        sudo dpkg -i google-chrome-stable_${CHROME_VERSION}-1_amd64.deb
        sudo apt-get install -f -y

    - name: Build with Gradle
      run: ./gradlew clean test
