name: Gradle build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '17'
        
    - name: Install headless Chrome
      run: |
        CHROME_VERSION=131.0.6778.264
        wget https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chrome-headless-shell-linux64.zip -O chrome-headless.zip
        unzip chrome-headless.zip -d chrome-headless
        sudo mv chrome-headless/chrome-headless-shell-linux64 /usr/local/bin/headless_shell/
        sudo chmod +x /usr/local/bin/headless_shell

    - name: Download and unzip ChromeDriver
      run: |
        CHROME_VERSION=131.0.6778.264
        wget https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chromedriver-linux64.zip -O chromedriver.zip
        unzip chromedriver.zip -d chromedriver
        mv chromedriver/chromedriver-linux64/chromedriver src/test/resources/chromedriver_linux
        chmod +x src/test/resources/chromedriver_linux

    - name: Validate Chrome installation
      run: /usr/local/bin/headless_shell --version

    - name: Validate ChromeDriver installation
      run: src/test/resources/chromedriver_linux --version

    - name: Install required utilities
      run: sudo apt-get install -y coreutils findutils

    - name: Run tests
      env:
        CHROME_BIN: /usr/local/bin/headless_shell
      run: ./gradlew clean test --info
