# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Gradle build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Install specific version of Chrome
      run: |
        CHROME_VERSION=131.0.6778.264
        wget https://dl.google.com/linux/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}-1_amd64.deb
        sudo dpkg -i google-chrome-stable_${CHROME_VERSION}-1_amd64.deb
        sudo apt-get install -f -y

    - name: Install required utilities
      run: sudo apt-get install -y coreutils findutils

    - name: Run tests
      run: ./gradlew clean test
